export type Country = { code: string; name: string; dial: string; flag: string };

// Liste exhaustive des pays/territoires avec indicatif téléphonique E.164 et drapeau emoji.
// Source: ITU-T E.164 + ISO 3166-1 alpha-2.
export const COUNTRIES: Country[] = [
  { code: "KM", name: "Comores", dial: "269", flag: "🇰🇲" },
  { code: "AF", name: "Afghanistan", dial: "93", flag: "🇦🇫" },
  { code: "ZA", name: "Afrique du Sud", dial: "27", flag: "🇿🇦" },
  { code: "AL", name: "Albanie", dial: "355", flag: "🇦🇱" },
  { code: "DZ", name: "Algérie", dial: "213", flag: "🇩🇿" },
  { code: "DE", name: "Allemagne", dial: "49", flag: "🇩🇪" },
  { code: "AD", name: "Andorre", dial: "376", flag: "🇦🇩" },
  { code: "AO", name: "Angola", dial: "244", flag: "🇦🇴" },
  { code: "AI", name: "Anguilla", dial: "1264", flag: "🇦🇮" },
  { code: "AQ", name: "Antarctique", dial: "672", flag: "🇦🇶" },
  { code: "AG", name: "Antigua-et-Barbuda", dial: "1268", flag: "🇦🇬" },
  { code: "SA", name: "Arabie saoudite", dial: "966", flag: "🇸🇦" },
  { code: "AR", name: "Argentine", dial: "54", flag: "🇦🇷" },
  { code: "AM", name: "Arménie", dial: "374", flag: "🇦🇲" },
  { code: "AW", name: "Aruba", dial: "297", flag: "🇦🇼" },
  { code: "AU", name: "Australie", dial: "61", flag: "🇦🇺" },
  { code: "AT", name: "Autriche", dial: "43", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaïdjan", dial: "994", flag: "🇦🇿" },
  { code: "BS", name: "Bahamas", dial: "1242", flag: "🇧🇸" },
  { code: "BH", name: "Bahreïn", dial: "973", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", dial: "880", flag: "🇧🇩" },
  { code: "BB", name: "Barbade", dial: "1246", flag: "🇧🇧" },
  { code: "BE", name: "Belgique", dial: "32", flag: "🇧🇪" },
  { code: "BZ", name: "Belize", dial: "501", flag: "🇧🇿" },
  { code: "BJ", name: "Bénin", dial: "229", flag: "🇧🇯" },
  { code: "BM", name: "Bermudes", dial: "1441", flag: "🇧🇲" },
  { code: "BT", name: "Bhoutan", dial: "975", flag: "🇧🇹" },
  { code: "BY", name: "Biélorussie", dial: "375", flag: "🇧🇾" },
  { code: "BO", name: "Bolivie", dial: "591", flag: "🇧🇴" },
  { code: "BQ", name: "Bonaire, Saint-Eustache et Saba", dial: "599", flag: "🇧🇶" },
  { code: "BA", name: "Bosnie-Herzégovine", dial: "387", flag: "🇧🇦" },
  { code: "BW", name: "Botswana", dial: "267", flag: "🇧🇼" },
  { code: "BR", name: "Brésil", dial: "55", flag: "🇧🇷" },
  { code: "BN", name: "Brunei", dial: "673", flag: "🇧🇳" },
  { code: "BG", name: "Bulgarie", dial: "359", flag: "🇧🇬" },
  { code: "BF", name: "Burkina Faso", dial: "226", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", dial: "257", flag: "🇧🇮" },
  { code: "KH", name: "Cambodge", dial: "855", flag: "🇰🇭" },
  { code: "CM", name: "Cameroun", dial: "237", flag: "🇨🇲" },
  { code: "CA", name: "Canada", dial: "1", flag: "🇨🇦" },
  { code: "CV", name: "Cap-Vert", dial: "238", flag: "🇨🇻" },
  { code: "CL", name: "Chili", dial: "56", flag: "🇨🇱" },
  { code: "CN", name: "Chine", dial: "86", flag: "🇨🇳" },
  { code: "CY", name: "Chypre", dial: "357", flag: "🇨🇾" },
  { code: "CO", name: "Colombie", dial: "57", flag: "🇨🇴" },
  { code: "CG", name: "Congo", dial: "242", flag: "🇨🇬" },
  { code: "CD", name: "Congo (RDC)", dial: "243", flag: "🇨🇩" },
  { code: "KP", name: "Corée du Nord", dial: "850", flag: "🇰🇵" },
  { code: "KR", name: "Corée du Sud", dial: "82", flag: "🇰🇷" },
  { code: "CR", name: "Costa Rica", dial: "506", flag: "🇨🇷" },
  { code: "CI", name: "Côte d'Ivoire", dial: "225", flag: "🇨🇮" },
  { code: "HR", name: "Croatie", dial: "385", flag: "🇭🇷" },
  { code: "CU", name: "Cuba", dial: "53", flag: "🇨🇺" },
  { code: "CW", name: "Curaçao", dial: "599", flag: "🇨🇼" },
  { code: "DK", name: "Danemark", dial: "45", flag: "🇩🇰" },
  { code: "DJ", name: "Djibouti", dial: "253", flag: "🇩🇯" },
  { code: "DM", name: "Dominique", dial: "1767", flag: "🇩🇲" },
  { code: "EG", name: "Égypte", dial: "20", flag: "🇪🇬" },
  { code: "SV", name: "Salvador", dial: "503", flag: "🇸🇻" },
  { code: "AE", name: "Émirats arabes unis", dial: "971", flag: "🇦🇪" },
  { code: "EC", name: "Équateur", dial: "593", flag: "🇪🇨" },
  { code: "ER", name: "Érythrée", dial: "291", flag: "🇪🇷" },
  { code: "ES", name: "Espagne", dial: "34", flag: "🇪🇸" },
  { code: "EE", name: "Estonie", dial: "372", flag: "🇪🇪" },
  { code: "SZ", name: "Eswatini", dial: "268", flag: "🇸🇿" },
  { code: "US", name: "États-Unis", dial: "1", flag: "🇺🇸" },
  { code: "ET", name: "Éthiopie", dial: "251", flag: "🇪🇹" },
  { code: "FK", name: "Falkland (Malouines)", dial: "500", flag: "🇫🇰" },
  { code: "FO", name: "Féroé (Îles)", dial: "298", flag: "🇫🇴" },
  { code: "FJ", name: "Fidji", dial: "679", flag: "🇫🇯" },
  { code: "FI", name: "Finlande", dial: "358", flag: "🇫🇮" },
  { code: "FR", name: "France", dial: "33", flag: "🇫🇷" },
  { code: "GA", name: "Gabon", dial: "241", flag: "🇬🇦" },
  { code: "GM", name: "Gambie", dial: "220", flag: "🇬🇲" },
  { code: "GE", name: "Géorgie", dial: "995", flag: "🇬🇪" },
  { code: "GS", name: "Géorgie du Sud et Sandwich du Sud", dial: "500", flag: "🇬🇸" },
  { code: "GH", name: "Ghana", dial: "233", flag: "🇬🇭" },
  { code: "GI", name: "Gibraltar", dial: "350", flag: "🇬🇮" },
  { code: "GR", name: "Grèce", dial: "30", flag: "🇬🇷" },
  { code: "GD", name: "Grenade", dial: "1473", flag: "🇬🇩" },
  { code: "GL", name: "Groenland", dial: "299", flag: "🇬🇱" },
  { code: "GP", name: "Guadeloupe", dial: "590", flag: "🇬🇵" },
  { code: "GU", name: "Guam", dial: "1671", flag: "🇬🇺" },
  { code: "GT", name: "Guatemala", dial: "502", flag: "🇬🇹" },
  { code: "GG", name: "Guernesey", dial: "44", flag: "🇬🇬" },
  { code: "GN", name: "Guinée", dial: "224", flag: "🇬🇳" },
  { code: "GQ", name: "Guinée équatoriale", dial: "240", flag: "🇬🇶" },
  { code: "GW", name: "Guinée-Bissau", dial: "245", flag: "🇬🇼" },
  { code: "GY", name: "Guyana", dial: "592", flag: "🇬🇾" },
  { code: "GF", name: "Guyane française", dial: "594", flag: "🇬🇫" },
  { code: "HT", name: "Haïti", dial: "509", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", dial: "504", flag: "🇭🇳" },
  { code: "HK", name: "Hong Kong", dial: "852", flag: "🇭🇰" },
  { code: "HU", name: "Hongrie", dial: "36", flag: "🇭🇺" },
  { code: "BV", name: "Île Bouvet", dial: "47", flag: "🇧🇻" },
  { code: "CX", name: "Île Christmas", dial: "61", flag: "🇨🇽" },
  { code: "IM", name: "Île de Man", dial: "44", flag: "🇮🇲" },
  { code: "NF", name: "Île Norfolk", dial: "672", flag: "🇳🇫" },
  { code: "KY", name: "Îles Caïmans", dial: "1345", flag: "🇰🇾" },
  { code: "CC", name: "Îles Cocos", dial: "61", flag: "🇨🇨" },
  { code: "CK", name: "Îles Cook", dial: "682", flag: "🇨🇰" },
  { code: "MH", name: "Îles Marshall", dial: "692", flag: "🇲🇭" },
  { code: "MP", name: "Îles Mariannes du Nord", dial: "1670", flag: "🇲🇵" },
  { code: "SB", name: "Îles Salomon", dial: "677", flag: "🇸🇧" },
  { code: "TC", name: "Îles Turques-et-Caïques", dial: "1649", flag: "🇹🇨" },
  { code: "VG", name: "Îles Vierges britanniques", dial: "1284", flag: "🇻🇬" },
  { code: "VI", name: "Îles Vierges des États-Unis", dial: "1340", flag: "🇻🇮" },
  { code: "IN", name: "Inde", dial: "91", flag: "🇮🇳" },
  { code: "ID", name: "Indonésie", dial: "62", flag: "🇮🇩" },
  { code: "IQ", name: "Irak", dial: "964", flag: "🇮🇶" },
  { code: "IR", name: "Iran", dial: "98", flag: "🇮🇷" },
  { code: "IE", name: "Irlande", dial: "353", flag: "🇮🇪" },
  { code: "IS", name: "Islande", dial: "354", flag: "🇮🇸" },
  { code: "IL", name: "Israël", dial: "972", flag: "🇮🇱" },
  { code: "IT", name: "Italie", dial: "39", flag: "🇮🇹" },
  { code: "JM", name: "Jamaïque", dial: "1876", flag: "🇯🇲" },
  { code: "JP", name: "Japon", dial: "81", flag: "🇯🇵" },
  { code: "JE", name: "Jersey", dial: "44", flag: "🇯🇪" },
  { code: "JO", name: "Jordanie", dial: "962", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", dial: "7", flag: "🇰🇿" },
  { code: "KE", name: "Kenya", dial: "254", flag: "🇰🇪" },
  { code: "KG", name: "Kirghizistan", dial: "996", flag: "🇰🇬" },
  { code: "KI", name: "Kiribati", dial: "686", flag: "🇰🇮" },
  { code: "XK", name: "Kosovo", dial: "383", flag: "🇽🇰" },
  { code: "KW", name: "Koweït", dial: "965", flag: "🇰🇼" },
  { code: "RE", name: "La Réunion", dial: "262", flag: "🇷🇪" },
  { code: "LA", name: "Laos", dial: "856", flag: "🇱🇦" },
  { code: "LS", name: "Lesotho", dial: "266", flag: "🇱🇸" },
  { code: "LV", name: "Lettonie", dial: "371", flag: "🇱🇻" },
  { code: "LB", name: "Liban", dial: "961", flag: "🇱🇧" },
  { code: "LR", name: "Libéria", dial: "231", flag: "🇱🇷" },
  { code: "LY", name: "Libye", dial: "218", flag: "🇱🇾" },
  { code: "LI", name: "Liechtenstein", dial: "423", flag: "🇱🇮" },
  { code: "LT", name: "Lituanie", dial: "370", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", dial: "352", flag: "🇱🇺" },
  { code: "MO", name: "Macao", dial: "853", flag: "🇲🇴" },
  { code: "MK", name: "Macédoine du Nord", dial: "389", flag: "🇲🇰" },
  { code: "MG", name: "Madagascar", dial: "261", flag: "🇲🇬" },
  { code: "MY", name: "Malaisie", dial: "60", flag: "🇲🇾" },
  { code: "MW", name: "Malawi", dial: "265", flag: "🇲🇼" },
  { code: "MV", name: "Maldives", dial: "960", flag: "🇲🇻" },
  { code: "ML", name: "Mali", dial: "223", flag: "🇲🇱" },
  { code: "MT", name: "Malte", dial: "356", flag: "🇲🇹" },
  { code: "MA", name: "Maroc", dial: "212", flag: "🇲🇦" },
  { code: "MQ", name: "Martinique", dial: "596", flag: "🇲🇶" },
  { code: "MU", name: "Maurice", dial: "230", flag: "🇲🇺" },
  { code: "MR", name: "Mauritanie", dial: "222", flag: "🇲🇷" },
  { code: "YT", name: "Mayotte", dial: "262", flag: "🇾🇹" },
  { code: "MX", name: "Mexique", dial: "52", flag: "🇲🇽" },
  { code: "FM", name: "Micronésie", dial: "691", flag: "🇫🇲" },
  { code: "MD", name: "Moldavie", dial: "373", flag: "🇲🇩" },
  { code: "MC", name: "Monaco", dial: "377", flag: "🇲🇨" },
  { code: "MN", name: "Mongolie", dial: "976", flag: "🇲🇳" },
  { code: "ME", name: "Monténégro", dial: "382", flag: "🇲🇪" },
  { code: "MS", name: "Montserrat", dial: "1664", flag: "🇲🇸" },
  { code: "MZ", name: "Mozambique", dial: "258", flag: "🇲🇿" },
  { code: "MM", name: "Myanmar (Birmanie)", dial: "95", flag: "🇲🇲" },
  { code: "NA", name: "Namibie", dial: "264", flag: "🇳🇦" },
  { code: "NR", name: "Nauru", dial: "674", flag: "🇳🇷" },
  { code: "NP", name: "Népal", dial: "977", flag: "🇳🇵" },
  { code: "NI", name: "Nicaragua", dial: "505", flag: "🇳🇮" },
  { code: "NE", name: "Niger", dial: "227", flag: "🇳🇪" },
  { code: "NG", name: "Nigéria", dial: "234", flag: "🇳🇬" },
  { code: "NU", name: "Niue", dial: "683", flag: "🇳🇺" },
  { code: "NO", name: "Norvège", dial: "47", flag: "🇳🇴" },
  { code: "NC", name: "Nouvelle-Calédonie", dial: "687", flag: "🇳🇨" },
  { code: "NZ", name: "Nouvelle-Zélande", dial: "64", flag: "🇳🇿" },
  { code: "OM", name: "Oman", dial: "968", flag: "🇴🇲" },
  { code: "UG", name: "Ouganda", dial: "256", flag: "🇺🇬" },
  { code: "UZ", name: "Ouzbékistan", dial: "998", flag: "🇺🇿" },
  { code: "PK", name: "Pakistan", dial: "92", flag: "🇵🇰" },
  { code: "PW", name: "Palaos", dial: "680", flag: "🇵🇼" },
  { code: "PS", name: "Palestine", dial: "970", flag: "🇵🇸" },
  { code: "PA", name: "Panama", dial: "507", flag: "🇵🇦" },
  { code: "PG", name: "Papouasie-Nouvelle-Guinée", dial: "675", flag: "🇵🇬" },
  { code: "PY", name: "Paraguay", dial: "595", flag: "🇵🇾" },
  { code: "NL", name: "Pays-Bas", dial: "31", flag: "🇳🇱" },
  { code: "PE", name: "Pérou", dial: "51", flag: "🇵🇪" },
  { code: "PH", name: "Philippines", dial: "63", flag: "🇵🇭" },
  { code: "PN", name: "Pitcairn", dial: "64", flag: "🇵🇳" },
  { code: "PL", name: "Pologne", dial: "48", flag: "🇵🇱" },
  { code: "PF", name: "Polynésie française", dial: "689", flag: "🇵🇫" },
  { code: "PR", name: "Porto Rico", dial: "1787", flag: "🇵🇷" },
  { code: "PT", name: "Portugal", dial: "351", flag: "🇵🇹" },
  { code: "QA", name: "Qatar", dial: "974", flag: "🇶🇦" },
  { code: "CF", name: "République centrafricaine", dial: "236", flag: "🇨🇫" },
  { code: "DO", name: "République dominicaine", dial: "1809", flag: "🇩🇴" },
  { code: "CZ", name: "République tchèque", dial: "420", flag: "🇨🇿" },
  { code: "RO", name: "Roumanie", dial: "40", flag: "🇷🇴" },
  { code: "GB", name: "Royaume-Uni", dial: "44", flag: "🇬🇧" },
  { code: "RU", name: "Russie", dial: "7", flag: "🇷🇺" },
  { code: "RW", name: "Rwanda", dial: "250", flag: "🇷🇼" },
  { code: "EH", name: "Sahara occidental", dial: "212", flag: "🇪🇭" },
  { code: "BL", name: "Saint-Barthélemy", dial: "590", flag: "🇧🇱" },
  { code: "KN", name: "Saint-Kitts-et-Nevis", dial: "1869", flag: "🇰🇳" },
  { code: "SM", name: "Saint-Marin", dial: "378", flag: "🇸🇲" },
  { code: "MF", name: "Saint-Martin (partie française)", dial: "590", flag: "🇲🇫" },
  { code: "SX", name: "Saint-Martin (partie néerlandaise)", dial: "1721", flag: "🇸🇽" },
  { code: "PM", name: "Saint-Pierre-et-Miquelon", dial: "508", flag: "🇵🇲" },
  { code: "VA", name: "Saint-Siège (Vatican)", dial: "379", flag: "🇻🇦" },
  { code: "VC", name: "Saint-Vincent-et-les-Grenadines", dial: "1784", flag: "🇻🇨" },
  { code: "SH", name: "Sainte-Hélène", dial: "290", flag: "🇸🇭" },
  { code: "LC", name: "Sainte-Lucie", dial: "1758", flag: "🇱🇨" },
  { code: "WS", name: "Samoa", dial: "685", flag: "🇼🇸" },
  { code: "AS", name: "Samoa américaines", dial: "1684", flag: "🇦🇸" },
  { code: "ST", name: "Sao Tomé-et-Principe", dial: "239", flag: "🇸🇹" },
  { code: "SN", name: "Sénégal", dial: "221", flag: "🇸🇳" },
  { code: "RS", name: "Serbie", dial: "381", flag: "🇷🇸" },
  { code: "SC", name: "Seychelles", dial: "248", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", dial: "232", flag: "🇸🇱" },
  { code: "SG", name: "Singapour", dial: "65", flag: "🇸🇬" },
  { code: "SK", name: "Slovaquie", dial: "421", flag: "🇸🇰" },
  { code: "SI", name: "Slovénie", dial: "386", flag: "🇸🇮" },
  { code: "SO", name: "Somalie", dial: "252", flag: "🇸🇴" },
  { code: "SD", name: "Soudan", dial: "249", flag: "🇸🇩" },
  { code: "SS", name: "Soudan du Sud", dial: "211", flag: "🇸🇸" },
  { code: "LK", name: "Sri Lanka", dial: "94", flag: "🇱🇰" },
  { code: "SE", name: "Suède", dial: "46", flag: "🇸🇪" },
  { code: "CH", name: "Suisse", dial: "41", flag: "🇨🇭" },
  { code: "SR", name: "Suriname", dial: "597", flag: "🇸🇷" },
  { code: "SJ", name: "Svalbard et Jan Mayen", dial: "47", flag: "🇸🇯" },
  { code: "SY", name: "Syrie", dial: "963", flag: "🇸🇾" },
  { code: "TJ", name: "Tadjikistan", dial: "992", flag: "🇹🇯" },
  { code: "TW", name: "Taïwan", dial: "886", flag: "🇹🇼" },
  { code: "TZ", name: "Tanzanie", dial: "255", flag: "🇹🇿" },
  { code: "TD", name: "Tchad", dial: "235", flag: "🇹🇩" },
  { code: "TF", name: "Terres australes françaises", dial: "262", flag: "🇹🇫" },
  { code: "IO", name: "Territoire britannique de l'océan Indien", dial: "246", flag: "🇮🇴" },
  { code: "TH", name: "Thaïlande", dial: "66", flag: "🇹🇭" },
  { code: "TL", name: "Timor oriental", dial: "670", flag: "🇹🇱" },
  { code: "TG", name: "Togo", dial: "228", flag: "🇹🇬" },
  { code: "TK", name: "Tokelau", dial: "690", flag: "🇹🇰" },
  { code: "TO", name: "Tonga", dial: "676", flag: "🇹🇴" },
  { code: "TT", name: "Trinité-et-Tobago", dial: "1868", flag: "🇹🇹" },
  { code: "TN", name: "Tunisie", dial: "216", flag: "🇹🇳" },
  { code: "TM", name: "Turkménistan", dial: "993", flag: "🇹🇲" },
  { code: "TR", name: "Turquie", dial: "90", flag: "🇹🇷" },
  { code: "TV", name: "Tuvalu", dial: "688", flag: "🇹🇻" },
  { code: "UA", name: "Ukraine", dial: "380", flag: "🇺🇦" },
  { code: "UY", name: "Uruguay", dial: "598", flag: "🇺🇾" },
  { code: "VU", name: "Vanuatu", dial: "678", flag: "🇻🇺" },
  { code: "VE", name: "Venezuela", dial: "58", flag: "🇻🇪" },
  { code: "VN", name: "Viêt Nam", dial: "84", flag: "🇻🇳" },
  { code: "WF", name: "Wallis-et-Futuna", dial: "681", flag: "🇼🇫" },
  { code: "YE", name: "Yémen", dial: "967", flag: "🇾🇪" },
  { code: "ZM", name: "Zambie", dial: "260", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", dial: "263", flag: "🇿🇼" },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // Comores
