/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReglesRouteImport } from './routes/regles'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaliTokenRouteImport } from './routes/wali.$token'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMonProfilRouteImport } from './routes/_authenticated/mon-profil'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDemandesRouteImport } from './routes/_authenticated/demandes'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as WaliTokenConvIdRouteImport } from './routes/wali.$token.$convId'
import { Route as AuthenticatedProfilIdRouteImport } from './routes/_authenticated/profil.$id'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminConversationsRouteImport } from './routes/_authenticated/admin.conversations'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin.users.$id'
import { Route as AuthenticatedAdminConversationsIdRouteImport } from './routes/_authenticated/admin.conversations.$id'

const ReglesRoute = ReglesRouteImport.update({
  id: '/regles',
  path: '/regles',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaliTokenRoute = WaliTokenRouteImport.update({
  id: '/wali/$token',
  path: '/wali/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonProfilRoute = AuthenticatedMonProfilRouteImport.update({
  id: '/mon-profil',
  path: '/mon-profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandesRoute = AuthenticatedDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const WaliTokenConvIdRoute = WaliTokenConvIdRouteImport.update({
  id: '/$convId',
  path: '/$convId',
  getParentRoute: () => WaliTokenRoute,
} as any)
const AuthenticatedProfilIdRoute = AuthenticatedProfilIdRouteImport.update({
  id: '/profil/$id',
  path: '/profil/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConversationsRoute =
  AuthenticatedAdminConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminConversationsIdRoute =
  AuthenticatedAdminConversationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/privacy': typeof PrivacyRoute
  '/regles': typeof ReglesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRoute
  '/demandes': typeof AuthenticatedDemandesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mon-profil': typeof AuthenticatedMonProfilRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/wali/$token': typeof WaliTokenRouteWithChildren
  '/admin/conversations': typeof AuthenticatedAdminConversationsRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/profil/$id': typeof AuthenticatedProfilIdRoute
  '/wali/$token/$convId': typeof WaliTokenConvIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/conversations/$id': typeof AuthenticatedAdminConversationsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/privacy': typeof PrivacyRoute
  '/regles': typeof ReglesRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/demandes': typeof AuthenticatedDemandesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mon-profil': typeof AuthenticatedMonProfilRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/wali/$token': typeof WaliTokenRouteWithChildren
  '/admin/conversations': typeof AuthenticatedAdminConversationsRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/profil/$id': typeof AuthenticatedProfilIdRoute
  '/wali/$token/$convId': typeof WaliTokenConvIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/conversations/$id': typeof AuthenticatedAdminConversationsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/privacy': typeof PrivacyRoute
  '/regles': typeof ReglesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/demandes': typeof AuthenticatedDemandesRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/mon-profil': typeof AuthenticatedMonProfilRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/wali/$token': typeof WaliTokenRouteWithChildren
  '/_authenticated/admin/conversations': typeof AuthenticatedAdminConversationsRouteWithChildren
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/_authenticated/profil/$id': typeof AuthenticatedProfilIdRoute
  '/wali/$token/$convId': typeof WaliTokenConvIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/conversations/$id': typeof AuthenticatedAdminConversationsIdRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgu'
    | '/connexion'
    | '/privacy'
    | '/regles'
    | '/admin'
    | '/conversations'
    | '/demandes'
    | '/home'
    | '/mon-profil'
    | '/onboarding'
    | '/parametres'
    | '/wali/$token'
    | '/admin/conversations'
    | '/admin/reports'
    | '/admin/users'
    | '/chat/$id'
    | '/profil/$id'
    | '/wali/$token/$convId'
    | '/admin/'
    | '/admin/conversations/$id'
    | '/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/connexion'
    | '/privacy'
    | '/regles'
    | '/conversations'
    | '/demandes'
    | '/home'
    | '/mon-profil'
    | '/onboarding'
    | '/parametres'
    | '/wali/$token'
    | '/admin/conversations'
    | '/admin/reports'
    | '/admin/users'
    | '/chat/$id'
    | '/profil/$id'
    | '/wali/$token/$convId'
    | '/admin'
    | '/admin/conversations/$id'
    | '/admin/users/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cgu'
    | '/connexion'
    | '/privacy'
    | '/regles'
    | '/_authenticated/admin'
    | '/_authenticated/conversations'
    | '/_authenticated/demandes'
    | '/_authenticated/home'
    | '/_authenticated/mon-profil'
    | '/_authenticated/onboarding'
    | '/_authenticated/parametres'
    | '/wali/$token'
    | '/_authenticated/admin/conversations'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/users'
    | '/_authenticated/chat/$id'
    | '/_authenticated/profil/$id'
    | '/wali/$token/$convId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/conversations/$id'
    | '/_authenticated/admin/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CguRoute: typeof CguRoute
  ConnexionRoute: typeof ConnexionRoute
  PrivacyRoute: typeof PrivacyRoute
  ReglesRoute: typeof ReglesRoute
  WaliTokenRoute: typeof WaliTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regles': {
      id: '/regles'
      path: '/regles'
      fullPath: '/regles'
      preLoaderRoute: typeof ReglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wali/$token': {
      id: '/wali/$token'
      path: '/wali/$token'
      fullPath: '/wali/$token'
      preLoaderRoute: typeof WaliTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-profil': {
      id: '/_authenticated/mon-profil'
      path: '/mon-profil'
      fullPath: '/mon-profil'
      preLoaderRoute: typeof AuthenticatedMonProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandes': {
      id: '/_authenticated/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof AuthenticatedDemandesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/wali/$token/$convId': {
      id: '/wali/$token/$convId'
      path: '/$convId'
      fullPath: '/wali/$token/$convId'
      preLoaderRoute: typeof WaliTokenConvIdRouteImport
      parentRoute: typeof WaliTokenRoute
    }
    '/_authenticated/profil/$id': {
      id: '/_authenticated/profil/$id'
      path: '/profil/$id'
      fullPath: '/profil/$id'
      preLoaderRoute: typeof AuthenticatedProfilIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/conversations': {
      id: '/_authenticated/admin/conversations'
      path: '/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AuthenticatedAdminConversationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/conversations/$id': {
      id: '/_authenticated/admin/conversations/$id'
      path: '/$id'
      fullPath: '/admin/conversations/$id'
      preLoaderRoute: typeof AuthenticatedAdminConversationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminConversationsRoute
    }
  }
}

interface AuthenticatedAdminConversationsRouteChildren {
  AuthenticatedAdminConversationsIdRoute: typeof AuthenticatedAdminConversationsIdRoute
}

const AuthenticatedAdminConversationsRouteChildren: AuthenticatedAdminConversationsRouteChildren =
  {
    AuthenticatedAdminConversationsIdRoute:
      AuthenticatedAdminConversationsIdRoute,
  }

const AuthenticatedAdminConversationsRouteWithChildren =
  AuthenticatedAdminConversationsRoute._addFileChildren(
    AuthenticatedAdminConversationsRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminConversationsRoute: typeof AuthenticatedAdminConversationsRouteWithChildren
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminConversationsRoute:
    AuthenticatedAdminConversationsRouteWithChildren,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDemandesRoute: typeof AuthenticatedDemandesRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMonProfilRoute: typeof AuthenticatedMonProfilRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
  AuthenticatedProfilIdRoute: typeof AuthenticatedProfilIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDemandesRoute: AuthenticatedDemandesRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMonProfilRoute: AuthenticatedMonProfilRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
  AuthenticatedProfilIdRoute: AuthenticatedProfilIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface WaliTokenRouteChildren {
  WaliTokenConvIdRoute: typeof WaliTokenConvIdRoute
}

const WaliTokenRouteChildren: WaliTokenRouteChildren = {
  WaliTokenConvIdRoute: WaliTokenConvIdRoute,
}

const WaliTokenRouteWithChildren = WaliTokenRoute._addFileChildren(
  WaliTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CguRoute: CguRoute,
  ConnexionRoute: ConnexionRoute,
  PrivacyRoute: PrivacyRoute,
  ReglesRoute: ReglesRoute,
  WaliTokenRoute: WaliTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
